### PR TITLE
[fix] Break circular barrel imports to resolve Jest worker OOM (#89)

### LINKED ISSUE #89: fix: parseCycleDashboard Jest worker OOM in packages/core test suite
## Problem

Running `npm test` from the repo root causes the `packages/core` Jest worker to crash with:

```
Jest worker ran out of memory and crashed
```

The failing test is `tests/core/utils/parser/parseCycleDashboard.test.ts`, introduced in #53 (lift-and-shift migration from GAS repo). The test suite runs `jest` with no `--maxWorkers` or heap-size configuration, so parallel worker memory is unbounded.

## Workaround (documented in CLAUDE.md)

```bash
npm test -w @lifting-logbook/core -- --runInBand
```

## Acceptance criteria

- [ ] `npm test` completes without OOM error from repo root
- [ ] Fix does not materially slow down the core test suite in CI
- [ ] `jest.config.base.js` or `packages/core/jest.config.js` updated as needed (e.g., `--maxWorkers`, `NODE_OPTIONS`, or test refactor to reduce peak allocation)

### LINKED ISSUE #92: [fix] TS2532 — apps/api cycle-generation.service.ts:69 Object is possibly undefined
## Problem

`apps/api/src/programs/cycle-generation.service.ts` line 69 uses `liftRecords[0].date` as the initial accumulator for a `reduce` call. TypeScript's strict array indexing treats `liftRecords[0]` as `LiftRecord | undefined`, producing:

```
error TS2532: Object is possibly 'undefined'.
```

This has been causing CI to fail on `main` since at least April 21, 2026.

## Root cause

TypeScript strict mode flags indexed array access as potentially `undefined`. The preceding guard (`liftRecords.length === 0` → throw) guarantees `liftRecords[0]` is defined, but TypeScript doesn't narrow through array length checks.

## Fix

Add a non-null assertion:

```ts
// Before
liftRecords[0].date,

// After  
liftRecords[0]!.date,
```

## Acceptance criteria

- [ ] `apps/api` builds without TypeScript errors
- [ ] CI `Lint & Test` check goes green

### PR DESCRIPTION
**Pull request by brownm09**
## Summary

- All source files within \`packages/core/src/\` were importing from the root \`@src/core\` barrel, which re-exports those same files — creating circular dependency chains that caused ts-jest workers to exhaust memory.
- Replaced every \`from \"@src/core\"\` inside \`src/\` with direct sub-path imports: \`@src/core/models\`, \`@src/core/constants\`, or \`@src/core/utils/jsUtil\`.
- Also fixes a pre-existing \`TS2532: Object is possibly 'undefined'\` in \`apps/api\` that had been failing CI since 2026-04-21 (tracked in #92).
- 18 files changed.

## Root cause (OOM)

\`packages/core/src/index.ts\` is a barrel that re-exports all sub-modules (\`catalog\`, \`constants\`, \`models\`, \`services\`, \`utils\`). Files within those sub-modules were themselves importing from \`@src/core\`, completing the cycle. ts-jest's module resolution entered a pathologically deep graph traversal and OOM'd the worker.

## Acceptance criteria

- [x] \`parseCycleDashboard.test.ts\` runs without OOM
- [x] Full core test suite (\`npm test -w @lifting-logbook/core\`) passes: **92 tests, 21 suites, all green**
- [x] No \`from \"@src/core\"\` barrel imports remain in \`packages/core/src/**\`
- [x] \`apps/api\` builds without TypeScript errors (fixes #92)

## Test plan

\`\`\`bash
npm test -w @lifting-logbook/core
# Expected: 92 passed, 21 suites, 0 failures
\`\`\`

Closes #89
Closes #92

🤖 Generated with [Claude Code](https://claude.com/claude-code)

### CODE REVIEW

**Comment by brownm09** [comment]
## Review: [fix] Break circular barrel imports to resolve Jest worker OOM (#89)

### Summary

Ready to merge. The fix is correct, complete, and well-scoped: all 17 files within `packages/core/src/` have had their `@src/core` barrel imports replaced with the appropriate sub-path (`@src/core/models`, `@src/core/constants`, or `@src/core/utils/jsUtil`), with no residual barrel imports remaining. The root-cause analysis in the PR description is accurate — the cycle was `file → barrel → file` — and breaking it is the right fix (not `--runInBand` or fixture trimming). No blocking findings.

---

### Non-Blocking Findings

**[maintainability]** `packages/core/src/services/dashboard/updateCycle.ts:5`

The pre-existing import `from "../../models/UpdateCycleOverrides"` uses a relative path while every adjacent import now uses `@src/core/models`. This inconsistency was not introduced by this PR but stands out once the sub-path pattern is fully established.

**Suggestion:** Add `UpdateCycleOverrides` to `packages/core/src/models/index.ts` (if it isn't already) and update this import to `from "@src/core/models"` in a follow-up.

---

**[maintainability]** `packages/core/jest.config.js` / `packages/core/package.json` (no specific line)

Nothing currently prevents a future contributor from inadvertently re-introducing `from "@src/core"` barrel imports inside `packages/core/src/`, which would silently re-create the cycle.

**Suggestion:** Add an ESLint [`no-restricted-imports`](https://eslint.org/docs/latest/rules/no-restricted-imports) rule in a follow-up to ban `from "@src/core"` within the `packages/core/src/` subtree.

---

### Style Notes

Import order is consistently applied throughout — constants first, models second, utils third, with relative imports last. The PR description is clear and contains an accurate root-cause explanation, acceptance criteria, and test plan — no changes needed there.

---

*Reviewed by `claude-sonnet-4-5` via Claude Code*
