### PR TITLE
[fix] Abuse-harden /api/client-errors: same-origin guard (observe→enforce)

### LINKED ISSUE #419: [fix] Local test failures on Node 24 — core Jest worker OOM and web route.test TS2576 NextResponse.json
## Symptom

Running `npm test` locally on Node 24 (Windows) against `origin/main` (commit `73f89a1`) produces the following pre-existing failures, unrelated to any code under test:

### packages/core — 6 suites OOM

```
FAIL tests/core/utils/parser/parseCycleDashboard.test.ts
FAIL tests/core/utils/jsUtil.test.ts
FAIL tests/core/services/workout/createGridV2.test.ts
FAIL tests/core/services/workout/updateLiftDates.test.ts
FAIL tests/core/services/bodyWeight.test.ts
FAIL tests/core/utils/import/validateLiftImport.test.ts
```

Each fails with:
```
Test suite failed to run
  Jest worker ran out of memory and crashed
    at ChildProcessWorker._onExit (../../node_modules/jest-worker/build/index.js:928:26)
```

Recurrence of the failure class previously fixed in #89 — appears to have regressed (or returned in a different form) under Node 24.

### apps/web — TS type errors in route handler tests

```
app/api/healthz/route.test.ts:65,66 — error TS2576:
  Property 'json' does not exist on type 'NextResponse<{ ok: boolean; }>'.
  Did you mean to access the static member 'NextResponse<{ ok: boolean; }>.json' instead?
```
Same class of error also surfaces in `app/livez/route.test.ts` and `lib/__tests__/programPlan.test.ts`.

This appears to be a `@types/next` / `next` type definition issue — `NextResponse` instances now disallow the instance `.json()` access these tests use.

## Suspected root cause

Local Node version is 24.13.0; CI runs Node 20 (per `.nvmrc`). The Node 24 caveat documented in [CLAUDE.md](https://github.com/brownm09/lifting-logbook/blob/main/CLAUDE.md) warns about install-time corruption but does not cover Jest worker memory pressure or `next` type drift under Node 24. CI is currently green for both packages, so this is a local-only failure mode at the moment.

## Why this matters

Blocks the pre-PR `npm test` gate for any local change. Currently being unblocked per CLAUDE.md failure-tracking rule by citing this issue in PR bodies.

## Acceptance criteria

- [ ] Identify whether Node 24 worker heap exhaustion is the root cause for the `packages/core` OOMs; if so, document the workaround (e.g., `--maxWorkers=2` or `NODE_OPTIONS=--max-old-space-size=4096`) or pin Jest config to handle it
- [ ] Investigate the `NextResponse.json` instance-vs-static-member type drift in the route handler tests; either update the test patterns or pin the relevant `@types/next` / `next` versions
- [ ] Confirm `npm test` passes locally on Node 24

## Workaround

Test suite passes in CI (Node 20). Local runs on Node 20 (`nvm use 20.11.1`) are expected to pass.

### LINKED ISSUE #806: [infra] Rate-limit / abuse-harden the unauthenticated /api/client-errors telemetry sink
## Problem

The `POST /api/client-errors` beacon sink added in #798 / PR #805 is **public and unauthenticated by necessity** (the failure it reports may itself be an auth expiry, so Clerk must not gate it — see `apps/web/middleware.ts`). It records a **retained ERROR span** per accepted request (status `ERROR` → kept by the ADR-020 tail-sampling `errors` policy).

Two independent reviews of PR #805 flagged this as an abuse / cost vector:

- **Cross-origin browser spam:** `sendBeacon` sends a CORS "simple" request, so a page on any origin can `navigator.sendBeacon('<app-origin>/api/client-errors', …)` from a victim's browser; the server currently ignores `Origin`.
- **Scripted spam:** trivial `curl` volume.

Each accepted request injects one always-retained ERROR span into the shared free-tier Grafana Cloud / Tempo stack. ADR-020 explicitly *rejected* per-policy rate limits and *rejected* relying on the ingest cap (it silently drops the newest spans), assuming a shape like this couldn't exist — a flood here could starve real production spans.

## Already mitigated in PR #805 (span *size*, not *rate*)

- `content-length` precheck before buffering + byte-accurate 4 KB body cap.
- 512-char clamp on every string attribute (including context keys), 24-key context cap, scalar-only context values.

## Deferred here (span *rate* / abuse)

1. **Infra-level rate limiting** (Cloud Armor / ingress / edge) for the unauthenticated endpoint — the robust fix for scripted abuse; out of scope for an app-level PR.
2. **A same-origin `Origin`-header check** in the handler to drop cross-origin browser beacons. Deferred from PR #805 because it must be validated in **staging** against the real proxy chain first: this is best-effort telemetry, so a false-drop (if `Origin.host !== Host` for legit same-origin traffic behind the LB) would silently kill the whole feature.
3. Consider an **ADR-020 addendum** documenting the accepted interim risk.

## Urgency

The abuse surface is currently **latent**: per #804, `apps/web` server spans do not reach prod Tempo yet (no web collector sidecar). This should be resolved **before / together with #804**, which is what makes these spans live in production.

Epic: Observability. Follows #798 / PR #805; coupled to #804.

### PR DESCRIPTION
**Pull request by brownm09**
## Summary

Abuse-hardens the public/unauthenticated `POST /api/client-errors` beacon sink (added in #798 / PR #805), which records **one retained ERROR span per accepted request** (the ADR-020 `errors` tail-sampling policy always keeps it). PR #805 bounded span **size**; this bounds cross-origin browser-beacon **rate** with a same-origin guard, and documents the accepted interim risk in an ADR-020 addendum.

The guard is **observe-only by default** and can only ever *drop* against an explicit allowlist — so it cannot silently kill this best-effort telemetry via a false-drop, which is exactly why #806 required staging validation before enforcement.

## What changed

- **`apps/web/app/api/client-errors/route.ts`** — a same-origin guard:
  - Every recorded span is tagged `client.origin.check` = `same-origin` | `cross-origin` | `no-origin` (always, even when nothing is dropped — the signal used to validate the guard in staging Tempo). Cross-origin verdicts also record the clamped offending origin as `client.origin.value`.
  - A request is **dropped** (204, before buffering the body or starting a span) only when it is classified `cross-origin` against the `CLIENT_ERROR_ALLOWED_ORIGINS` allowlist **and** `CLIENT_ERROR_DROP_CROSS_ORIGIN=true`.
  - **Safety interlock:** the zero-config `Origin`-host-vs-`Host` heuristic (whose risk is an LB rewriting `Host`) is used only to produce the observe verdict — it **never drops**. If `DROP` is on but no allowlist is set, the request is recorded and flagged `client.origin.enforce_skipped=true`, never dropped. So a production drop is impossible without an operator-reviewed allowlist.
  - `no-origin` (curl / non-browser) is never dropped — scripted abuse is deferred to an infra rate limit (#808).
- **`apps/web/app/api/client-errors/route.test.ts`** — 9 new tests (observe tagging, allowlist-over-Host, opaque `null` origin, enforce-drop, enforce-record, no-origin-under-enforce, the enforce_skipped interlock). All 10 pre-existing tests unchanged & green.
- **`docs/adr/ADR-020-*.md`** — `## Addendum — 2026-07-10 (#806)`: documents the accepted interim risk (an unauthenticated always-retained ERROR-span source is a shape the ADR's rejected alternatives assumed couldn't exist), the three layered mitigations (size #805 → origin guard #806 → infra rate limit #808), and the enable-enforcement procedure. Adds WHATWG Fetch + MDN sendBeacon references.
- **`docs/adr-references.md`** — indexes the two new sources.
- **`CLAUDE.md`** — Observability note extended with the guard + its two env vars.

## Acceptance criteria (from #806)

- [x] **(2) Same-origin `Origin`-header check** to drop cross-origin browser beacons — landed, observe→enforce, allowlist-gated so the staging-validation-first constraint is honoured.
- [x] **(3) ADR-020 addendum** documenting the accepted interim risk.
- [ ] **(1) Infra-level rate limiting** (Cloud Armor / edge) for scripted abuse — explicitly out of scope for an app-level PR; filed as **#808**.
- [ ] **Enable enforcement** after staging validation of the guard — needs the real proxy chain; filed as **#809** (coupled to #804).

## Testing

`npm run typecheck` — **passed** (web executed, others cached).

`npm test -w @lifting-logbook/web`:

```
Tests:       259 passed, 0 skipped, 0 failed (54.6 s)
Test Suites: 2 failed (worker OOM at load), 42 passed, 44 total
```

- The client-errors suite: **19 passed** (10 pre-existing + 9 new).
- The 2 "failed" suites (`StepImport.test.tsx`, `StepLifts.test.tsx`) crashed at **load** with `Jest worker ran out of memory` — **not** assertion failures (every test that ran passed). They pass cleanly in isolation:
  ```
  npx jest --config apps/web/jest.config.js --runInBand "StepImport.test|StepLifts.test"
  → Test Suites: 2 passed, 2 total; Tests: 18 passed
  ```
  This is the documented Windows full-suite parallel-load worker-OOM flake (prior workarounds in the now-closed #419 / #567 don't fully cover these two CSV-heavy suites). Local-Windows-only; CI (Linux, Node 20) is unaffected. Tracked in **#807**. Unrelated to this change (different files).

**Pre-PR gates:** suppression grep (ADR-026) clean · test-integrity grep (ADR-029) clean · no deleted tests · no `package.json` change (lockfile gate N/A).

## Risk-dimension audit

- **Testing** — per-branch Jest node-env coverage for the new guard (9 tests).
- **Observability** — this *is* an observability control. New attributes are non-secret (Origin/Host only, no auth material), clamped to 512 chars. Retained-span **count** is unchanged in observe mode and reduced under enforcement. Repo audit items 1–3 (raw SQL / LLM PII / payload redaction) N/A — headers only, no SQL, no LLM, no bodies logged.
- **Security** — shrinks the abuse surface; fail-open (any error → record, never 500/blackout). Endpoint public by design (privilege-restricted-test rule N/A).
- **Resilience** — never throws/500; instant rollback by unsetting `CLIENT_ERROR_DROP_CROSS_ORIGIN` (no code deploy); enforcement gated so misconfig can't blackout.
- **Performance** — O(1) header reads + one `URL` parse; enforce rejects **before** buffering the body — strictly less work than today.
- **Data integrity / migrations** — N/A (no schema / data change).

## Follow-ups

- **#807** — web onboarding CSV-heavy suites still OOM under Windows full-suite parallel load.
- **#808** — infra-level rate limit (Cloud Armor / edge) for the endpoint (deferred item 1).
- **#809** — staging-validate the guard and enable enforcement (deferred item 2's enforcement step; coupled to #804).

Closes #806

## Review findings disposition

Review: [comment](https://github.com/brownm09/lifting-logbook/pull/810#issuecomment-4941561114) — `blocking=0 non_blocking=1`.

- **[reliability] allowlist trailing-slash normalization** — **fixed in `1561591`**: `parseAllowedOrigins` now strips a trailing slash from each entry (a serialized `Origin` never has one), preventing a silent enforce-mode false-drop from a `https://host/`-style config typo. Regression test added; client-errors suite 20/20 green.

### CODE REVIEW

**Comment by brownm09** [comment]
## Review: [fix] Abuse-harden /api/client-errors: same-origin guard (observe→enforce)

### Summary
**Merge-ready.** The change adds a same-origin guard to the public/unauthenticated client-error beacon sink, scoped so it can only ever *drop* against an explicit operator allowlist — the zero-config `Origin`-host-vs-`Host` heuristic is observe-only and never drops. That honours #806's "validate in staging before enforcing" constraint and makes a silent telemetry blackout via false-drop structurally impossible in production. The handler fails open, never 500s, and rejects cross-origin beacons before buffering the body. One non-blocking robustness gap (allowlist trailing-slash normalization) was found and fixed during review (`1561591`). Highest-severity item: that one non-blocking finding — now resolved.

Note the abuse surface is **not closed by this PR alone**: in the default observe mode cross-origin spam is still recorded (tagged, not dropped). Enforcement (#809) must be flipped after staging validation — acceptable because the surface stays latent until #804 wires web spans to prod Tempo.

Gate checks: test-coverage ✓ (9→10 new tests), test-integrity ✓ (no skips/deletions; `Tests:` summary present), ADR-warrant ✓ (ADR-020 dated addendum in diff), doc-reconciliation n/a (no Documentation Maintenance table), README coverage ✓ (no ancestor READMEs).

---

### Non-Blocking Findings

**[reliability]** `apps/web/app/api/client-errors/route.ts` — `parseAllowedOrigins`
Allowlist entries were matched by exact string, but a serialized `Origin` header never carries a trailing slash. An operator copying `https://app.example.com/` (the trailing-slash form a browser address bar shows) into `CLIENT_ERROR_ALLOWED_ORIGINS` would classify every legitimate same-origin beacon as `cross-origin` and — once `CLIENT_ERROR_DROP_CROSS_ORIGIN=true` — silently drop it: the exact telemetry-blackout the guard's observe-only default exists to prevent.
**Suggestion:** Strip trailing slashes from allowlist entries when parsing. → **Fixed in this PR (`1561591`)**, with a regression test.

---

### Findings Disposition
- **[reliability]** allowlist trailing-slash normalization — **fixed in `1561591`** (`parseAllowedOrigins` now strips trailing slashes; regression test added, suite 20/20 green).

---

*Reviewed by `claude-opus-4-8` via Claude Code*

**Comment by brownm09** [comment]
## Review (refresh): [fix] Abuse-harden /api/client-errors: same-origin guard

Re-posted to refresh the Review Gate marker after merging `origin/main` into the branch to satisfy `strict` up-to-date (merge commit `9aefd1a` pulled in unrelated #811 dep changes only — none of the reviewed files changed). The [original review](https://github.com/brownm09/lifting-logbook/pull/810#issuecomment-4941561114) stands.

**Verdict:** merge-ready. `blocking=0`, `non_blocking=1` — the one non-blocking finding (allowlist trailing-slash normalization) was found and **fixed in-PR (`1561591`)**, disposition recorded in the PR body.

Gate checks: test-coverage ✓ · test-integrity ✓ (`Tests:` summary present) · ADR-warrant ✓ (ADR-020 dated addendum) · doc-reconciliation n/a · README coverage ✓.

---

*Reviewed by `claude-opus-4-8` via Claude Code*
